# Site settings
title: TNF 10주년 기념
email: contact@needlworks.org
description: > # this means to ignore newlines until "baseurl:"
  태터앤프렌즈/태터네트워크재단 (TNF) 이 10주년을 맞이했습니다.
baseurl: "/10yr-anniversary" # the subpath of your site, e.g. /blog/
url: "http://www.needlworks.org" # the base hostname & protocol for your site
twitter_username: textcube
github_username:  textcube_dev

# Build settings
markdown: kramdown
