# Site settings
title: 2015년 4월 14일 - TNF 10년!
email: contact@needlworks.org
description: > # this means to ignore newlines until "baseurl:"
  태터앤프렌즈/태터네트워크재단 (TNF) 10년
baseurl: "/10yr-anniversary" # the subpath of your site, e.g. /blog/
url: "http://www.needlworks.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
